spring:
  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password: example
    driver-class-name: com.mysql.jdbc.Driver

---
spring:
  profiles: travis
  jpa:
    hibernate:
      ddl-auto: create

  datasource:
    url: jdbc:mysql://localhost:3306
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver