spring:
  datasource:
    url: jdbc:mysql://localhost:3306/DinnerService?useSSL=false
    username: root
    password: example
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

---
spring:
  profiles: travis
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  datasource:
    url: jdbc:mysql://localhost:3306/DinnerService?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver