language: java
jdk: oraclejdk8
sudo: false

script:
  - cd backend
  - mvn verify -Dspring.profiles.active=travis -Dspring.output.ansi.enabled=always
  - cd ..
  
services:
  - mysql
  - docker
  
cache:
  directories:
  - .autoconf
  - $HOME/.m2
  - $HOME/google-cloud-sdk/
  
env:
  global:
    - GOOGLE_APPLICATION_CREDENTIALS=~/gcloud-service-key.json
    - PROJECT_NAME_STG=foodful-stg
    - CLUSTER_NAME_STG=foodful-stg
    - PROJECT_NAME_PRD=foodful-prod
    - CLUSTER_NAME_PRD=foodful-prod
    - CLOUDSDK_COMPUTE_ZONE=europe-north1-a    
    - DOCKER_IMAGE_NAME_DINNER=dinner
    - DOCKER_IMAGE_NAME_AUTH=auth
    - DOCKER_IMAGE_NAME_GATEWAY=gateway
    - DOCKER_IMAGE_NAME_USER=user    
    - KUBE_DEPLOYMENT_NAME_DINNER=dinner-service
    - KUBE_DEPLOYMENT_NAME_AUTH=auth-service
    - KUBE_DEPLOYMENT_NAME_GATEWAY=gateway-service
    - KUBE_DEPLOYMENT_NAME_USER=user-service    
    - KUBE_DEPLOYMENT_CONTAINER_NAME_DINNER=dinner
    - KUBE_DEPLOYMENT_CONTAINER_NAME_AUTH=auth
    - KUBE_DEPLOYMENT_CONTAINER_NAME_GATEWAY=gateway
    - KUBE_DEPLOYMENT_CONTAINER_NAME_USER=user
  
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS DinnerService;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS AuthService;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS UserService;'
  
before_deploy:
  - if [ ! -d "$HOME/google-cloud-sdk/bin" ]; then rm -rf $HOME/google-cloud-sdk; export CLOUDSDK_CORE_DISABLE_PROMPTS=1; curl https://sdk.cloud.google.com | bash; fi
  - source /home/travis/google-cloud-sdk/path.bash.inc
  - gcloud --quiet version
  - gcloud --quiet components update
  - gcloud --quiet components update kubectl
  
deploy:
  - provider: script
    script: ./deploy-staging.sh
    skip_cleanup: true
    on:
      branch: dev
  - provider: script
    script: ./deploy-production.sh
    skip_cleanup: true
    on:
      branch: master
