script:
  - cd backend
  - mvn verify -Dspring.profiles.active=travis -Dspring.output.ansi.enabled=always
  
services:
  - mysql
  
cache:
  directories:
  - .autoconf
  - $HOME/.m2
  
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS DinnerService;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS AuthService;'
  - mysql -e 'CREATE DATABASE IF NOT EXISTS UserService;'

language: java
jdk: oraclejdk8