script:
  - cd backend
  - mvn verify -Dspring.profiles.active=travis -Dspring.output.ansi.enabled=always
  
services:
  - mysql
  
before_install:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS DinnerService;'

language: java
jdk: oraclejdk8