apiVersion: v1
kind: Service
metadata:
  labels:
    app: auth
  name: auth-service
  namespace: default
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: auth
  sessionAffinity: None
  type: ClusterIP

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: auth
  name: auth
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: eu.gcr.io/foodful-stg/auth:latest
          imagePullPolicy: Always
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://localhost:3306/AuthService?useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: cloudsql-db-credentials
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: cloudsql-db-credentials
            - name: FOODFUL_SOCIAL_AUTH_FACEBOOK_CLIENT-SECRET
              valueFrom:
                secretKeyRef:
                  key: client-secret
                  name: fb-api-credentials
            - name: FOODFUL_SOCIAL_AUTH_FACEBOOK_CLIENT-ID
              valueFrom:
                secretKeyRef:
                  key: client-id
                  name: fb-api-credentials
          livenessProbe:
            httpGet:
                path: /actuator/health
                port: 8080
            initialDelaySeconds: 30
            periodSeconds: 30
                  
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          imagePullPolicy: IfNotPresent        
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          command:
            - /cloud_sql_proxy
            - -instances=foodful-stg:europe-north1:foodful-stg-db=tcp:3306
            - -credential_file=/secrets/cloudsql/credentials.json
          volumeMounts:
          - mountPath: /secrets/cloudsql
            name: cloudsql-instance-credentials
            readOnly: true
            
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          defaultMode: 420
          secretName: cloudsql-instance-credentials
