apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-10-21T14:25:08Z
  generation: 1
  labels:
    app: auth
  name: auth
  namespace: default
  resourceVersion: "26279"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/auth
  uid: 1c7e413b-d53d-11e8-bf47-42010aa60177
spec:
  replicas: 3
  selector:
    matchLabels:
      app: auth
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: auth
    spec:
      containers:
        - name: auth
          image: eu.gcr.io/foodful-stg/auth:latest
          imagePullPolicy: Always
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://localhost:3306/AuthService?useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: cloudsql-db-credentials
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: cloudsql-db-credentials
          livenessProbe:
            httpGet:
                path: /actuator/health
                port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
                  
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          imagePullPolicy: IfNotPresent        
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          command:
            - /cloud_sql_proxy
            - -instances=foodful-stg:europe-north1:foodful-stg-db=tcp:3306
            - -credential_file=/secrets/cloudsql/credentials.json
          volumeMounts:
          - mountPath: /secrets/cloudsql
            name: cloudsql-instance-credentials
            readOnly: true
            
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          defaultMode: 420
          secretName: cloudsql-instance-credentials
