apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-10-21T12:29:39Z
  generation: 3
  labels:
    app: gateway
  name: gateway
  namespace: default
  resourceVersion: "15290"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/gateway
  uid: fa9dc26f-d52c-11e8-bf47-42010aa60177
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gateway
    spec:
      containers:
      - image: eu.gcr.io/foodful-stg/gateway:latest
        imagePullPolicy: Always
        name: gateway
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
