apiVersion: v1
kind: Service
metadata:
  labels:
    app: gateway
  name: gateway-service
  namespace: default
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30054
    port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: gateway
  sessionAffinity: None
  type: LoadBalancer
    
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: gateway
  name: gateway
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: gateway
    spec:
      containers:
      - image: eu.gcr.io/foodful-stg/gateway:latest
        imagePullPolicy: Always
        name: gateway
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        livenessProbe:
           httpGet:
               path: /actuator/health
               port: 8080
           initialDelaySeconds: 30
           periodSeconds: 30
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
