foodful:
  auth:
    user-data-header: X-Foodful-User
    token-header: Authorization
  clients:
    prefix: http://
    postfix: .internal

spring:
  cloud:
    gateway:
      routes:
      - id: dinner_route
        uri: http://dinner-service-v1.internal
        predicates:
        - Path=/dinner-service/v1/**
        filters:
        - AuthenticatedRequestFilter
      - id: auth_route
        uri: http://auth-service-v1.internal
        predicates:
        - Path=/auth-service/v1/**
