spring:
  datasource:
    url: jdbc:mysql://localhost:3306/AuthService?useSSL=false
    username: root
    password: example
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL57Dialect
        jdbc:
          time_zone: UTC
foodful:
  auth:
    user-data-header: X-Foodful-User
    jwt:
      key: 3jfef4e2e7cb44b2893169cd7c276824
    token:
      access:
        length: 50
        expires-in-minutes: 5
      refresh:
        length: 50
        expires-in-hours: 720
      cleanup-frequency-in-minutes: 10
    social:
      facebook:
        url: https://graph.facebook.com
        client-secret: INSERT_SECRET_HERE
        client-id: INSERT_ID_HERE
  clients:
    prefix: http://
    postfix:

---
spring:
  profiles: travis
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        jdbc:
          time_zone: UTC

  datasource:
    url: jdbc:mysql://localhost:3306/AuthService?useSSL=false
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver