apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-10-21T17:35:46Z
  generation: 1
  labels:
    app: gateway
  name: gateway
  namespace: default
  resourceVersion: "30111"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/gateway
  uid: fa7e63f2-d546-11e8-89fb-42010aa6020d
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gateway
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: gateway
    spec:
      containers:
      - image: eu.gcr.io/foodful-prod/gateway:latest
        imagePullPolicy: Always
        name: gateway
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        livenessProbe:
            httpGet:
                path: /actuator/health
                port: 8080
            initialDelaySeconds: 30
            periodSeconds: 5
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30

