apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "1"
  creationTimestamp: 2018-10-21T15:38:55Z
  generation: 1
  labels:
    app: user
  name: user
  namespace: default
  resourceVersion: "30495"
  selfLink: /apis/extensions/v1beta1/namespaces/default/deployments/user
  uid: 6b67012d-d547-11e8-89fb-42010aa6020d
spec:
  replicas: 3
  selector:
    matchLabels:
      app: user
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: user
    spec:
      containers:
        - name: user
          image: eu.gcr.io/foodful-prod/user:latest
          imagePullPolicy: Always
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          env:
            - name: SPRING_DATASOURCE_URL
              value: jdbc:mysql://localhost:3306/UserService?useSSL=false
            - name: SPRING_DATASOURCE_USERNAME
              valueFrom:
                secretKeyRef:
                  key: username
                  name: cloudsql-db-credentials
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  key: password
                  name: cloudsql-db-credentials
                  
        - name: cloudsql-proxy
          image: gcr.io/cloudsql-docker/gce-proxy:1.11
          imagePullPolicy: IfNotPresent        
          resources: {}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          command:
            - /cloud_sql_proxy
            - -instances=foodful-prod:europe-north1:foodful-prod-db=tcp:3306
            - -credential_file=/secrets/cloudsql/credentials.json
          volumeMounts:
          - mountPath: /secrets/cloudsql
            name: cloudsql-instance-credentials
            readOnly: true
            
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - name: cloudsql-instance-credentials
        secret:
          defaultMode: 420
          secretName: cloudsql-instance-credentials
